"""
Generative UI & Visual Explanation Schema Layer (Phase 9 Integration)
Grounded in Generative UI & XAI Visual Narrative Architecture Specification.

Defines Pydantic models for structured visual specs generated by Agent Jane:
- VisualizationSpec (Charts, Predictions, Pump Curves, Scenarios, Timelines, Evidence Graphs, Metrics, Tables)
- ExplanationSpec (Visual XAI Narratives: Observation, Evidence, Visual, Uncertainty, Recommendation)
"""

from typing import Dict, Any, List, Optional, Literal
from pydantic import BaseModel, Field


class ChartSpec(BaseModel):
    """Plotly/Vega-Lite Chart Spec Payload."""
    chart_engine: Literal["plotly", "vega_lite"] = "plotly"
    data: List[Dict[str, Any]] = Field(default_factory=list, description="Series/trace data objects")
    layout: Dict[str, Any] = Field(default_factory=dict, description="Plotly/Vega layout configuration")


class PredictionSpec(BaseModel):
    """24h Production/Head Forecast Spec with confidence bands."""
    forecast_horizon_hours: int = 24
    unit: str = "BPD"
    actual_series: Dict[str, Any] = Field(default_factory=dict)
    predicted_series: Dict[str, Any] = Field(default_factory=dict)
    upper_confidence_bound: List[float] = Field(default_factory=list)
    lower_confidence_bound: List[float] = Field(default_factory=list)


class ScenarioSpec(BaseModel):
    """VSD Frequency & Operating Point What-If Comparison Spec."""
    base_frequency_hz: float = 60.0
    scenarios: List[Dict[str, Any]] = Field(
        default_factory=list,
        description="List of scenario dicts, e.g. [{'frequency_hz': 55, 'flow_bpd': 1450, 'tdh_ft': 3900}]"
    )
    recommended_frequency_hz: Optional[float] = None


class PumpCurveSpec(BaseModel):
    """ESP Pump Performance H-Q Curve with Operating Point Overlay."""
    pump_model: str
    rated_bep_bpd: float
    operating_flow_bpd: float
    operating_tdh_ft: float
    operating_region: Literal["OPTIMAL", "DOWNTHRUST", "UPTHRUST"]
    head_curve_points: List[Dict[str, float]] = Field(default_factory=list)
    efficiency_curve_points: List[Dict[str, float]] = Field(default_factory=list)


class EventTimelineItem(BaseModel):
    """Timeline event item."""
    event_id: str
    timestamp: str
    severity: Literal["LOW", "MEDIUM", "HIGH", "CRITICAL"]
    summary: str
    source: str = "SCADA"


class TimelineSpec(BaseModel):
    """Operational Event & Alert Timeline Spec."""
    events: List[EventTimelineItem] = Field(default_factory=list)


class EvidenceGraphSpec(BaseModel):
    """Visual Evidence & Causal Graph Spec (Mermaid / GraphSpec)."""
    graph_type: Literal["mermaid", "causal_nodes"] = "mermaid"
    mermaid_definition: str = ""
    nodes: List[Dict[str, Any]] = Field(default_factory=list)
    edges: List[Dict[str, Any]] = Field(default_factory=list)


class MetricCardSpec(BaseModel):
    """KPI Metric Summary Card Spec."""
    metric_id: str
    label: str
    value: Any
    unit: Optional[str] = None
    status: Literal["HEALTHY", "WARNING", "FAULT", "NEUTRAL"] = "NEUTRAL"
    trend: Optional[Literal["UP", "DOWN", "STABLE"]] = None


class TableSpec(BaseModel):
    """Structured Data Table Spec."""
    columns: List[str] = Field(default_factory=list)
    rows: List[Dict[str, Any]] = Field(default_factory=list)


class VisualizationSpec(BaseModel):
    """
    Unified Contract for all Generative UI Elements.
    The Agent backend produces validated instances of this spec; the React UI renders them.
    """
    vis_id: str = Field(description="Unique visualization identifier")
    type: Literal[
        "plotly_chart",
        "prediction",
        "pump_curve",
        "scenario",
        "timeline",
        "evidence_graph",
        "metric",
        "table"
    ]
    title: str
    data_ref: List[str] = Field(default_factory=list)
    evidence_ids: List[str] = Field(default_factory=list)
    
    # Specific spec payloads (only active type populated)
    chart: Optional[ChartSpec] = None
    prediction: Optional[PredictionSpec] = None
    scenario: Optional[ScenarioSpec] = None
    pump_curve: Optional[PumpCurveSpec] = None
    timeline: Optional[TimelineSpec] = None
    evidence_graph: Optional[EvidenceGraphSpec] = None
    metric: Optional[MetricCardSpec] = None
    table: Optional[TableSpec] = None


class ExplanationSection(BaseModel):
    """Single section inside a visual XAI explanation narrative."""
    section_type: Literal[
        "observation",
        "evidence",
        "inference",
        "uncertainty",
        "constraint",
        "recommendation",
        "visual"
    ]
    title: str
    text: str
    evidence_ids: List[str] = Field(default_factory=list)
    visualization_ref: Optional[str] = None


class ExplanationSpec(BaseModel):
    """
    Structured Visual Narrative Specification.
    Combines text observations, evidence bindings, confidence levels, and inline visualization references.
    """
    explanation_id: str
    title: str
    primary_hypothesis: str
    confidence_score: float = Field(ge=0.0, le=1.0)
    sections: List[ExplanationSection] = Field(default_factory=list)
    visualizations: List[VisualizationSpec] = Field(default_factory=list)
